- The query joins the employees table with itself to link each employee to their manager.
- e represents the employee and m represents the manager.
- The join condition matches an employee’s manager_id with the manager’s id.
- The WHERE clause compares salaries of employees and their managers.
- Only employees who earn more than their managers are returned.